-- HSQLDB
CREATE TABLE titulo (
	codigo INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	descricao VARCHAR(60) NOT NULL,
	data_vencimento DATE NOT NULL,
	valor DECIMAL NOT NULL,
	status VARCHAR(20) NOT NULL
);

INSERT INTO titulo (descricao, data_vencimento, valor, status) values ('Condominio Apto 102', '2017-06-10', 130.00, 'RECEBIDO');